#define BLEND_BASE_ADDR 0x40000000

#define BLEND_AP_CTRL         (*((volatile uint32_t *)(BLEND_BASE_ADDR + 0x00)))
#define BLEND_AP_BKGND_0      (*((volatile uint32_t *)(BLEND_BASE_ADDR + 0x18)))
#define BLEND_AP_BKGND_1      (*((volatile uint32_t *)(BLEND_BASE_ADDR + 0x1C)))
#define BLEND_AP_FRGND_0      (*((volatile uint32_t *)(BLEND_BASE_ADDR + 0x24)))
#define BLEND_AP_FRGND_1      (*((volatile uint32_t *)(BLEND_BASE_ADDR + 0x28)))

#define LCD0_SPI_TEST_0        (*((volatile uint32_t *)(XPAR_LCD_SPI_0_BASEADDR + 0x00)))
#define LCD0_SPI_TEST_1        (*((volatile uint32_t *)(XPAR_LCD_SPI_0_BASEADDR + 0x04)))
#define LCD0_SPI_TEST_2        (*((volatile uint32_t *)(XPAR_LCD_SPI_0_BASEADDR + 0x08)))
#define LCD0_SPI_TEST_3        (*((volatile uint32_t *)(XPAR_LCD_SPI_0_BASEADDR + 0x0c)))
#define LCD0_SPI_TIMEBASE_LOAD (*((volatile uint32_t *)(XPAR_LCD_SPI_0_BASEADDR + 0x10)))
#define LCD0_SPI_TIMEBASE_FLAG (*((volatile uint32_t *)(XPAR_LCD_SPI_0_BASEADDR + 0x14)))
#define LCD0_SPI_GPIO          (*((volatile uint32_t *)(XPAR_LCD_SPI_0_BASEADDR + 0x18)))
#define LCD0_SPI_8B_DATA       (*((volatile uint32_t *)(XPAR_LCD_SPI_0_BASEADDR + 0x1C)))
#define LCD0_SPI_SRLZ_STAT     (*((volatile uint32_t *)(XPAR_LCD_SPI_0_BASEADDR + 0x20)))

#define LCD1_SPI_TEST_0        (*((volatile uint32_t *)(XPAR_LCD_SPI_1_BASEADDR + 0x00)))
#define LCD1_SPI_TEST_1        (*((volatile uint32_t *)(XPAR_LCD_SPI_1_BASEADDR + 0x04)))
#define LCD1_SPI_TEST_2        (*((volatile uint32_t *)(XPAR_LCD_SPI_1_BASEADDR + 0x08)))
#define LCD1_SPI_TEST_3        (*((volatile uint32_t *)(XPAR_LCD_SPI_1_BASEADDR + 0x0c)))
#define LCD1_SPI_TIMEBASE_LOAD (*((volatile uint32_t *)(XPAR_LCD_SPI_1_BASEADDR + 0x10)))
#define LCD1_SPI_TIMEBASE_FLAG (*((volatile uint32_t *)(XPAR_LCD_SPI_1_BASEADDR + 0x14)))
#define LCD1_SPI_GPIO          (*((volatile uint32_t *)(XPAR_LCD_SPI_1_BASEADDR + 0x18)))
#define LCD1_SPI_8B_DATA       (*((volatile uint32_t *)(XPAR_LCD_SPI_1_BASEADDR + 0x1C)))
#define LCD1_SPI_SRLZ_STAT     (*((volatile uint32_t *)(XPAR_LCD_SPI_1_BASEADDR + 0x20)))

#define LCD2_SPI_TEST_0        (*((volatile uint32_t *)(XPAR_LCD_SPI_2_BASEADDR + 0x00)))
#define LCD2_SPI_TEST_1        (*((volatile uint32_t *)(XPAR_LCD_SPI_2_BASEADDR + 0x04)))
#define LCD2_SPI_TEST_2        (*((volatile uint32_t *)(XPAR_LCD_SPI_2_BASEADDR + 0x08)))
#define LCD2_SPI_TEST_3        (*((volatile uint32_t *)(XPAR_LCD_SPI_2_BASEADDR + 0x0c)))
#define LCD2_SPI_TIMEBASE_LOAD (*((volatile uint32_t *)(XPAR_LCD_SPI_2_BASEADDR + 0x10)))
#define LCD2_SPI_TIMEBASE_FLAG (*((volatile uint32_t *)(XPAR_LCD_SPI_2_BASEADDR + 0x14)))
#define LCD2_SPI_GPIO          (*((volatile uint32_t *)(XPAR_LCD_SPI_2_BASEADDR + 0x18)))
#define LCD2_SPI_8B_DATA       (*((volatile uint32_t *)(XPAR_LCD_SPI_2_BASEADDR + 0x1C)))
#define LCD2_SPI_SRLZ_STAT     (*((volatile uint32_t *)(XPAR_LCD_SPI_2_BASEADDR + 0x20)))

#define LCD3_SPI_TEST_0        (*((volatile uint32_t *)(XPAR_LCD_SPI_3_BASEADDR + 0x00)))
#define LCD3_SPI_TEST_1        (*((volatile uint32_t *)(XPAR_LCD_SPI_3_BASEADDR + 0x04)))
#define LCD3_SPI_TEST_2        (*((volatile uint32_t *)(XPAR_LCD_SPI_3_BASEADDR + 0x08)))
#define LCD3_SPI_TEST_3        (*((volatile uint32_t *)(XPAR_LCD_SPI_3_BASEADDR + 0x0c)))
#define LCD3_SPI_TIMEBASE_LOAD (*((volatile uint32_t *)(XPAR_LCD_SPI_3_BASEADDR + 0x10)))
#define LCD3_SPI_TIMEBASE_FLAG (*((volatile uint32_t *)(XPAR_LCD_SPI_3_BASEADDR + 0x14)))
#define LCD3_SPI_GPIO          (*((volatile uint32_t *)(XPAR_LCD_SPI_3_BASEADDR + 0x18)))
#define LCD3_SPI_8B_DATA       (*((volatile uint32_t *)(XPAR_LCD_SPI_3_BASEADDR + 0x1C)))
#define LCD3_SPI_SRLZ_STAT     (*((volatile uint32_t *)(XPAR_LCD_SPI_3_BASEADDR + 0x20)))

