compile: 
	arduino-cli compile --fqbn esp32:esp32:m5stack-atom atom-lite-rlcd-fuck-spinner.ino

upload:
	arduino-cli upload -p /dev/ttyUSB0 --fqbn esp32:esp32:m5stack-atom atom-lite-rlcd-fuck-spinner.ino

